### ISSUE TITLE
Dive into tailwind usage in rust

### ISSUE THREAD

**Issue by SaraVieira** [axodotdev/oranda#15]
https://docs.rs/tailwind-css/latest/tailwind_css/

**Comment by SaraVieira** [comment]
After a bunch of exhaustive search it seems there are two options:

- https://docs.rs/tailwind-css/latest/tailwind_css/ → It does not work, simply adding it to a project breaks it, the project itself does not compile
- https://github.com/pintariching/railwind/ → It seems to work but for now only supports getting tailwind classes from HTML and not from CSS files and that is what we are using. Opened an issue asking to be sure:  https://github.com/pintariching/railwind/issues/4


Non-working changes were pushed to the `tailwin` branch

**Comment by ashleygwilliams** [comment]
@SaraVieira looks like you got some replies! i think it could be rad to work with them?

**Comment by sarahghp** [comment]
Closing in favor of: https://github.com/axodotdev/oranda/issues/59
