### ISSUE TITLE
header has too small of a top margin

### ISSUE THREAD

**Issue by steveklabnik** [axodotdev/oranda#166]
![image](https://user-images.githubusercontent.com/27786/217398890-cf2c9a9b-e3fe-4131-8d41-c2e5a1c50251.png)

this has good spacing below, but above it's smaller and feels cramped, imho

**Comment by SaraVieira** [comment]
Fixed in another repo where our CSS is but look at this aligned baby

![image](https://user-images.githubusercontent.com/1051509/217839520-7b928fb1-6792-4cc6-b4da-a47de1643c68.png)
