### ISSUE TITLE
no recommended download for my OS

### ISSUE THREAD

**Issue by steveklabnik** [axodotdev/oranda#167]
It would be nice if the install page helped guide me to the right triple. I see some other issues about some sort of detect OS functionality, but when I check my network tab, that JS isn't being loaded, and I don't see it in the source HTML either.

**Comment by ashleygwilliams** [comment]
@steveklabnik we've merged a few things in today- can you let us know if you still have this issue?

if so, could you take a screen cap for us and also let us know what `window.os` returns in your console? thanks!!

**Comment by steveklabnik** [comment]
screenshot 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/27786/217945980-714602fd-9679-4e10-b7ed-fab1c07697ab.png">

```console
> window.os
'64-windows-pc'
```

**Comment by SaraVieira** [comment]
ohhh, the idea is that you only really open this page if we can't detect it on the homepage, any idea how we could direct the user here?

We do now load the JS here

**Comment by steveklabnik** [comment]
>  the idea is that you only really open this page if we can't detect it on the homepage

The homepage shows me 
<img width="668" alt="image" src="https://user-images.githubusercontent.com/27786/217947778-f1eada82-16de-4168-939a-210024253dd3.png">

which just leads to that page, so I'm not sure if it's working on the homepage either.

> any idea how we could direct the user here?

https://rustup.rs/ is one example of a possibility; they show only the one relevant to my platform and then have a link to expand to other platforms. This is a product question really, so what you do specifically is more of a call for you all than for me :)

**Comment by ashleygwilliams** [comment]
@steveklabnik when you have the homepage open can you run `window.os` in your browser console and tell us what it says

the home page is trying to detect your OS and is failing for some reason.. e.g. it shows me this (on a mac silicon):
<img width="1005" alt="Screen Shot 2023-02-09 at 4 27 05 PM" src="https://user-images.githubusercontent.com/1163554/217953474-fffd8c91-e9e6-43c3-9909-3b47682013f3.png">

**Comment by steveklabnik** [comment]
Same as on the other page, `'64-windows-pc'`.

**Comment by ashleygwilliams** [comment]
sorry, didn't see under the image. investigating now. thanks for the info!

**Comment by steveklabnik** [comment]
I believe I have sorted it out.

```console
> getOS();
'64-windows-pc'
```

this is working properly. The issue:

```javascript
let hit = Array.from(document.querySelectorAll(".target[data-targets]")).find(
  (a) => a.attributes["data-targets"].value.includes(os)
);
```

if i check this in my console, `hit` is `undefined`. It's trying to find a `data-targets` with `64-windows-pc`, but the actual `data-targets` in the HTML is `x86_64-pc-windows-msvc`, so `hit` is undefined and I get the backup logic.

**Comment by SaraVieira** [comment]
god, our detection is backwards and we need to switch from `pc-windows` to `windows-pc`

**Comment by steveklabnik** [comment]
Success!
