### ISSUE TITLE
Add support for aarch64-apple-darwin architecture

### ISSUE THREAD

**Issue by pomdtr** [axodotdev/oranda#198]
I tried to run the installer script, and was met with this error:

```
ERROR: there isn't a package for aarch64-apple-darwin
```

**Comment by ashleygwilliams** [comment]
arm mac support was added to cargo-dist in version 0.0.4- to support this platform we need to make a new release of oranda - the next release will be 0.0.2 and i'm hoping that we can get that done today/monday :)

**Comment by pomdtr** [comment]
Thanks ! I saw somewhere that supports for mdbook was planned (or already implemented), are there some instructions available ?

**Comment by ashleygwilliams** [comment]
hi! yes- mdbook is supported and already on main. we haven't officially released oranda yet - so the docs are not in the best place but you can see an example in the cargo-dist repo:

- config: https://github.com/axodotdev/cargo-dist/blob/main/cargo-dist/oranda.json#L11 (takes a single key that represents the path to your *built* mdbook)
- ci: https://github.com/axodotdev/cargo-dist/blob/main/.github/workflows/web.yml (note that CI installs mdbook and builds the book, then runs oranda)

i'm hoping to auto generate the CI for folks in #188 - the main thing is that oranda won't *build* your mdbook for you (yet?) but can grab your built mdbook for you and publish it as part of your site.

**Comment by pomdtr** [comment]
Perfect! I'm really interested in the project, but i'll wait for the first release before adopting it.
