### ISSUE TITLE
feature request: create json schema for oranda

### ISSUE THREAD

**Issue by pomdtr** [axodotdev/oranda#264]
Currently Oranda options documentation is scattered between multiple files.

It would be to have all of these options described in a json schema, published on: https://www.schemastore.org/json

Here is the list of editors that support fetching completions from schemastore

<img width="910" alt="image" src="https://user-images.githubusercontent.com/17577332/232328314-7d6f3750-8b58-4e8b-a80b-a2e2c02a916a.png">

**Comment by Gankra** [comment]
prototype in #361

**Comment by manyinsects** [comment]
merged, so closing
