### ISSUE TITLE
lists in changelog bodies should have bullets

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#266]
<img width="526" alt="Screenshot 2023-04-17 at 1 54 09 PM" src="https://user-images.githubusercontent.com/1163554/232583718-1d2af3b8-e6c7-4a0a-8d27-ddd3bdb6a761.png">

**Comment by pomdtr** [comment]
Same thing on the README:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/17577332/233137100-9712d5bb-56b1-4198-9d41-77978fc3a396.png">
