### ISSUE TITLE
Avoid showing cargo-dist release body

### ISSUE THREAD

**Issue by manyinsects** [axodotdev/oranda#273]
`cargo-dist`'s release body, which shows up when you have changelogs enabled in oranda, as well as `cargo-dist` integration, but don't actually have a `CHANGELOG/RELEASE.md`, break the page layout by going over the viewport's width. I'm not sure if this is a bug (as the defined fallback for this case is an empty string), but we should avoid showing this either way.

**Comment by manyinsects** [comment]
probably related to #253

**Comment by ashleygwilliams** [comment]
@shadows-withal can you add screencaps and/or a repro repo- this is interesting and i'm wondering what exactly it does. when you have cargo-dist enabled, the changelog feature uses the announcement changelog, which is different than the release body - but i am not sure i have tested this with a repo that doesn't have a changelog/releases.md

**Comment by manyinsects** [comment]
will do as soon as i remember what this issue is about

**Comment by ashleygwilliams** [comment]
circling back up on this, @shadows-withal

**Comment by manyinsects** [comment]
looks like this was fixed since it happened, building my test site where it occurred with the latest main doesn't make it show anymore :+1:
