### ISSUE TITLE
Menu link ordering for additional pages is arbitrary

### ISSUE THREAD

**Issue by manyinsects** [axodotdev/oranda#283]
On one page of my local generated site:

![CleanShot 2023-05-04 at 10 54 48@2x](https://user-images.githubusercontent.com/6445316/236157384-d9e953ae-529f-4466-8c88-f7f68ed5acde.png)

And on the other:

![CleanShot 2023-05-04 at 10 55 30@2x](https://user-images.githubusercontent.com/6445316/236157439-f678027b-8e7c-4115-a33d-eb30ee4586c7.png)

Not sure why this happens exactly, `config.additional_pages` is set pretty early on and not changed after, and the layout header just iterates through that. Maybe it's somehow a CSS issue?

**Comment by ashleygwilliams** [comment]
heh, the order of a hashmaps keys is not guaranteed! we originally had a vector, which let you order them, perhaps this should be a vector of objects and/or we should introduce frontmatter which we could use to get the name

**Comment by ashleygwilliams** [comment]
gankra recently added a lib for an index map which if my memory serves, should preserve order- this is probably a quick fix

**Comment by Gankra** [comment]
We should probably also respect order in package_managers wrt tabs/artifacts.html. Right now I sort them by name but that doesn't have to be the case.

**Comment by Gankra** [comment]
This might have been fixed by #418, but I haven't tested to be 100% sure

**Comment by Gankra** [comment]
Page order is now deterministically

* Home
* additional_pages in declaration order
* Install
* Docs
* Changelog

![image](https://github.com/axodotdev/oranda/assets/1136864/fd5b522f-a2f3-4360-a48c-a48f2a7518c6)
