### ISSUE TITLE
just setting "repository" in oranda.json makes no index.html

### ISSUE THREAD

**Issue by Gankra** [axodotdev/oranda#304]
Testing oranda out on one of my projects, at this commit:

https://github.com/Gankra/socc-pair/commit/bbfe8418b3b67ee58d3027f2a4c292548dc8af25

With this oranda.json:

```json
{ "repository":"https://github.com/Gankra/socc-pair" }
```

produces this

![image](https://github.com/axodotdev/oranda/assets/1136864/653fb285-7de3-418f-97a4-916cb5f70549)

If I remove that key it returns to the normal "just read the README" behaviour.

**Comment by ashleygwilliams** [comment]
fixed by #297
