### ISSUE TITLE
issues if cargo-dist enabled but haven't yet published with it

### ISSUE THREAD

**Issue by Gankra** [axodotdev/oranda#305]
"Can't have artifacts header with no artifacts"

You can see this on https://github.com/Gankra/socc-pair

with 

```json
{
    "repository":"https://github.com/Gankra/socc-pair",
    "artifacts": { "cargo_dist": true }
}
```

We should just warn and move on, I think? This isn't the nicest behaviour for someone trying to bring everything up at once who just wants to try things out without running cargo-dist in prod.

**Comment by Gankra** [comment]
This is no longer a crash, but with #382 this situation can be *auto-detected* and you get completely empty widgets/pages 
![image](https://github.com/axodotdev/oranda/assets/1136864/2c67a400-7b6a-4646-be50-52cb00a31d29)

**Comment by Gankra** [comment]
This would be solved with #397.

**Comment by Gankra** [comment]
This is essentially fixed now. You can get an empty "install" page with this precise config, but that's basically fine if you're going to publish Soon and you can force it off with cargo_dist: false.

**Comment by Gankra** [comment]
Gonna reopen to signify decision on to what extent we should show empty UI to say "yep you enabled this, but we have no content"

**Comment by Gankra** [comment]
We now show this in the empty case

![image](https://github.com/axodotdev/oranda/assets/1136864/0f9d5a5f-fce0-4502-845f-d21c572ff7d7)

**Comment by Gankra** [comment]
criteria for for-reals closing this: make the widget and install page consistent

By doing exactly one of these two options:

* Making the Install Page hide when empty
* Making the Widget show when empty

**Comment by ashleygwilliams** [comment]
should be finished, test to be sure
