### ISSUE TITLE
do not default syntax highlighting to rust

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#310]
currently, oranda will assume that an unlabeled code block should be highlighted as rust code. this is a default in mdbook, and works well for rust projects. however, oranda supports all sorts of projects. we should update the code to only default to rust for rust projects. we can default highlighting to js for js projects, and then text for others.

https://github.com/axodotdev/oranda/blob/main/src/site/markdown/syntax_highlight/mod.rs#L67 is where this default exists

**Comment by 0xkelvin** [comment]
Hello @ashleygwilliams , i am 0xqwert#2911 on Discord.

I can't find any place invokes this function : https://github.com/axodotdev/oranda/blob/main/src/site/markdown/mod.rs#L17
I trying to trace where is the "**lang**" parameter comes from. I saw other place where pass "**Some("sh")**" as "**lang**" parameter. 
<img width="319" alt="image" src="https://github.com/axodotdev/oranda/assets/56182747/d55c4550-aebd-4534-b38d-0e171a88dff8">

**Comment by 0xkelvin** [comment]
ah, i guess i can find the answer somewhere from here : https://github.com/axodotdev/oranda/blob/main/tests/config/mod.rs#L66

**Comment by ashleygwilliams** [comment]
hey @0xkelvin - the lang is read using library functionality - you'll want to look here: https://github.com/axodotdev/oranda/blob/main/src/site/markdown/syntax_highlight/mod.rs#L16-L18

this code is then used as an adapter to `comrak` when the markdown is being parsed here: https://github.com/axodotdev/oranda/blob/f3b1220f518c60a58e153a3ae2255384d6628da1/src/site/markdown/mod.rs#L55

**Comment by 0xkelvin** [comment]
@ashleygwilliams ya, i got it. thanks

might i confirm my understanding: 

<img width="340" alt="image" src="https://github.com/axodotdev/oranda/assets/56182747/4df76c80-636a-4625-ae7f-d7e487384ed5">

- if oranda detects Rust project, the default of unlabeled code block is Rust
- if oranda detects JS project, the default of unlabeled code block is JS
- ..

**Comment by ashleygwilliams** [comment]
so currently, it will always default to rust, regardless of the project type. ideally, if we can detect the project type we should default to its base language. we can only currently detect js and rust projects so as you said:

-  if we find rust- default to rust (preserve current behavior)
- if we find js default to js (new behavior)
- if we don't know default to text (new behavior)

**Comment by 0xkelvin** [comment]
OK. 
now need to find the way to pass this into function : 
```
    /// The kinf of workspace this is (Rust or Javascript)
    pub kind: WorkspaceKind,
```

**Comment by ashleygwilliams** [comment]
hey @0xkelvin i don't think you should need to pass anything to that function. the primary modifications should be to this match statement: https://github.com/axodotdev/oranda/blob/main/src/site/markdown/syntax_highlight/mod.rs#L66.

some pseudo code:

```rust
let language = match lang {
        None | Some("") => default_highlight(ProjectType),
        Some("text") => "txt",
        Some("shell") => "sh",
        Some(l) => l,
    };
    
    fn default_highlight(project: ProjectType) -> String {
          match project {
               JavaScript => "js",
               Rust => "rs",
               _ => "txt",
           }
    }
 ```

**Comment by 0xkelvin** [comment]
@ashleygwilliams 
i totally got it
but only concern is how to extract the project type inside the **syntax_highlight** function ?

**Comment by ashleygwilliams** [comment]
hey @0xkelvin - so the project type is read by the [axoproject](https://github.com/axodotdev/axoproject) library here: https://github.com/axodotdev/oranda/blob/main/src/config/project/mod.rs#L115. We'll want to save the "[WorkspaceKind](https://github.com/axodotdev/axoproject/blob/main/src/lib.rs#L102)" and pass it through (probably as config or context) to the syntax highlight function - this is probably the trickiest part of this issue, so feel free to keep asking questions! cc @shadows-withal

**Comment by 0xkelvin** [comment]
> OK. now need to find the way to pass this into function :
> 
> ```
>     /// The kinf of workspace this is (Rust or Javascript)
>     pub kind: WorkspaceKind,
> ```

ya, that is why i came up with this, 
let me read the code more, i feel more familiar with the code base

**Comment by 0xkelvin** [comment]
@ashleygwilliams 

i think it is constraint by 
'**highlight**' function signature, originally from another trait (comrak)
https://github.com/axodotdev/oranda/blob/25c53389414cb196005e4dd0146270848f3a8ab9/src/site/markdown/mod.rs#L16-L19

**Comment by proofconstruction** [comment]
To resolve this issue, all that should be needed is to change [this match expression](https://github.com/axodotdev/oranda/blob/main/src/site/markdown/syntax_highlight/mod.rs#L66) from this:

``` rust
let language = match lang {
    None | Some("") => "rs",
    Some("text") => "txt",
    Some("shell") => "sh",
    Some(l) => l,
};
```
to this:
``` rust
let language = match lang {
    Some("rust")  => "rs",
    Some("javascript") => "js",
    Some("shell") => "sh",
    None | Some("") | Some("text") | Some(_) => "txt"
};
```
The `Some(l) => l` pattern gets removed because we want to default all uncaught patterns (captured by `Some(_)`) to `"txt"`, instead of whatever the original string was. The `lang: Option<&str>` is compared against each pattern in order and falls to the catch-all at the bottom (becoming "txt") if nothing matches.

---

This will become pretty annoying to update for more languages, though, and the goal is to support _many_. Instead of adding more patterns to this block for every language under the sun, in this case it might be better to create a new file like `src/site/markdown/syntax_highlight/supported_languages.rs`, and in there define the following:
- a list of pairs, where the first element of each pair is a string (or list of strings) representing the pattern(s) to match on, and the second element is the target string ("rs", "js", "txt", etc.), for example:
```rust
const LANGUAGE_PATTERNS: &[(&str,&str)] = &[
    ("rust", "rs"),
    ("javascript", "js"),
    ("shell", "sh"),
];
```
- a macro that takes the previous list and expands it out into the `match` block.

Then import that module into `src/site/markdown/syntax_highlight/mod.rs` and use the generated `match` block here.

**Comment by ashleygwilliams** [comment]
hey @proofconstruction that's not quite right- the issue issue here is not mapping a long name to a short one, but to manage the default for the `""` case. @0xkelvin is right, he needs to find a way to pass `WorkspaceKind` into the syntaxhighlight Adapter so that we can know whether to map `""` to `rs` or to `js` or to `text` based on the kind of workspace.

i would recommend for now that the best strategy is to just pass it through and we may introduce a struct similar to `Context ` or `Config` to collect it in.

**Comment by proofconstruction** [comment]
Ah I misunderstood. If the empty string case is mapped to anything other than `txt`, won't we end up highlighting a lot of shell with the wrong highlighter? I usually see people leaving fenced code blocks containing shell syntax untagged, rather than specifically tagging them with `bash` or other.

**Comment by ashleygwilliams** [comment]
@proofconstruction yeah- it's a bit odd. so the original feature comes from mdbook defaults- which defaults all code highlighting to rust if nothing is listed. a lot of folks are used to that and so the idea we had was to preserve that for folks with rust projects, and then default to js for js projects and text for anything else (we can only detect rust and js right now).

i am definitely mixed on the feature, but i do know it is a bug to default un annotated codeblock to rust in non-rust projects so i want that to change at the very least.

**Comment by manyinsects** [comment]
Opened #453 to push for a "correct" approach to this that doesn't require a larger code change (as we're operating under a time constraint here, unfortunately).
