### ISSUE TITLE
changelog parsing fails:  invalid type: null, expected a string

### ISSUE THREAD

**Issue by andrewmd5** [axodotdev/oranda#347]
I'm toying around with the project; I set my repo to 'https://github.com/betwixt-labs/bebop' and when building I get:
```
↪ >o_o< INFO: Adding changelog...

  × Failed parsing response when fetching releases from Github.
  ├─▶ error decoding response body: invalid type: null, expected a string at line 1 column 238414
  ╰─▶ invalid type: null, expected a string at line 1 column 238414
```

**Comment by ashleygwilliams** [comment]
hey @AndrewMD5 - thanks for filing and trying out the project. i've reproduced and am gonna dig in :) if you want- we have a discord you can join https://discord.gg/5m7tqr2eGr
