### ISSUE TITLE
Copy over local images

### ISSUE THREAD

**Issue by SaraVieira** [axodotdev/oranda#35]
When creating a markdown file I want to link to images that are stored locally on my machine and I want these to work on the produced HTML site and right now these images do not get copied over to the dist folder

File structure and names should be maintained

let's say you have an image linked as so `  ![Kirby](./games/kirby.png)` it should be copied to `dist/games/kirby.png`

**Comment by SaraVieira** [comment]
How it was done in the JS verison

https://github.com/axodotdev/oranda-js/blob/e94e58ac363adbec0b96d959896a47db5461255d/src/utils/steps/images.js#L4

**Comment by SaraVieira** [comment]
Reference https://docs.rs/regex/latest/regex/

**Comment by ashleygwilliams** [comment]
i think we should maybe do this with a local assets path list- not use a regex.. this would allow us to move stuff like html files or other assets

**Comment by SaraVieira** [comment]
So people would have to list all images they use?

**Comment by ashleygwilliams** [comment]
or put them in a single static dir, yes (which i think is reasonable...)

**Comment by SaraVieira** [comment]
I think we should allow them aywhere, we should make people chamnge the way they use mardkown because of oranda, that's the whole premise in my opinion, no changes and you get an HTML page

**Comment by ashleygwilliams** [comment]
i disagree, i think that randomly globbing img-like assets from a repo is gonna get us into trouble and it's hard to predict. putting assets in a static folder, or explicitly listing them doesn't require you to change how you use markdown.

**Comment by SaraVieira** [comment]
After a discussion it's been pointed out this issue is not genric enough and we need to copy over any static assets and for that this issue has been closed in favor of https://github.com/axodotdev/oranda/issues/47
