### ISSUE TITLE
release badge is not working

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#380]
<img width="138" alt="Screenshot 2023-06-14 at 7 45 05 AM" src="https://github.com/axodotdev/oranda/assets/1163554/64a5e7f9-5c54-4022-84be-ec8ad942178f">

this badge always says no status - it's not clear to me why, but we should investigate and either fix or remove it

**Comment by manyinsects** [comment]
This doesn't work because afaik release always builds on a detached head - we have `?branch=main` which will never be true, as we don't run that workflow on main, only tags.
