### ISSUE TITLE
cut back on the amount of vertical padding

### ISSUE THREAD

**Issue by Gankra** [axodotdev/oranda#394]
This is exacerbated by the new installer widget but i think it's also just pre-existing, we have a lot of space between chunks of the page 
![image](https://github.com/axodotdev/oranda/assets/1136864/68255f93-85aa-44df-91f1-7f014d825eee)

**Comment by manyinsects** [comment]
Looking at it now, with the reduced padding of the installer widget, on my monitor height the readme content starts at half the page height, which I think is perfectly reasonable, and the other places don't look too bad too, so I'm closing this for now

![image](https://github.com/axodotdev/oranda/assets/6445316/91c7a4ac-724e-4aa9-8d7b-69aa2e78c7d7)
