### ISSUE TITLE
orogene FUNDING.yml fails to parse

### ISSUE THREAD

**Issue by Gankra** [axodotdev/oranda#395]
https://github.com/orogene/orogene/blob/main/.github/FUNDING.yml

trying to test oranda on orogene (delete the old `md_book`  key from oranda.json, then `oranda dev`), but it both detects the FUNDING.yml and then also dies cryptically: 

```
  × Error while parsing FUNDING.yml
  help: Make sure your FUNDING.yml conforms to GitHub's format!
```

**Comment by ashleygwilliams** [comment]
i think this may be malformed- the `open collective` key points at nothing... i'll have to see what the "spec" says but i feel like that's invalid yml?

**Comment by ashleygwilliams** [comment]
yeah, i think this fails because it's not valid- github also does not render it: 
<img width="358" alt="Screenshot 2023-06-16 at 8 15 54 PM" src="https://github.com/axodotdev/oranda/assets/1163554/5cf35541-0f15-4e44-8f7b-1de5b51e4905">

i'm gonna close
