### ISSUE TITLE
additional pages should take an empty array

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#402]
<img width="629" alt="Screenshot 2023-06-19 at 12 24 40 PM" src="https://github.com/axodotdev/oranda/assets/1163554/c6bc8931-322f-4114-b120-d50e18709bf2">

**Comment by Gankra** [comment]
can you elaborate on the purpose of this over just omitting the key?

**Comment by Gankra** [comment]
This was misremembering that this value is an object -- `{}` is a valid value.
