### ISSUE TITLE
package managers values should be an array

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#403]

**Comment by Gankra** [comment]
Say more?

**Comment by ashleygwilliams** [comment]
thsi came out of some confusion with @SaraVieira when i was doing our UX walk through- i am wondering why our package manage config is a hashmap and not say, and array of objects - i think "should" in the title here is strong, but our intuitions were that it would be an array and it was surprising when it was not

**Comment by Gankra** [comment]
we could certainly make it an array of objects, but at that point i would invert "additional" and "preferred" to be flags/enums hanging off of each entry, instead of things they're nested under, since the only ergonomics win from the current solution seems lost.

**Comment by ashleygwilliams** [comment]
yeah, i'm pretty 50/50 on how to handle this- on one hand this makes it clear that the pacakage managers section is "content data" and aligns the preferred, additional, hidden as all vecs, on the other- is it redundant? do you have any pref?

**Comment by Gankra** [comment]
At this point I just don't want us to touch existing config structure anymore.

**Comment by ashleygwilliams** [comment]
this ship sailed, maybe if we ship big config changes in the future we can reconsider it
