### ISSUE TITLE
Do a pass on build output

### ISSUE THREAD

**Issue by Gankra** [axodotdev/oranda#431]
Right now we print a lot of unimportant stuff all the time, and it makes it hard for our warnings to stand out.

**Comment by manyinsects** [comment]
![image](https://github.com/axodotdev/oranda/assets/6445316/ce719f16-742e-48ce-becb-3ced7e1c7bf7)

**Comment by manyinsects** [comment]
we can probably get by with even less:

![image](https://github.com/axodotdev/oranda/assets/6445316/d79d9247-55d0-44d2-8702-8ce82df93b77)
