### ISSUE TITLE
show universal installers even if auto detecting assets doesn't include platform

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#446]
repro, run oranda on https://github.com/pomdtr/sunbeam

on mac it shows "nothing for ya" but if you click into the identified platforms it shows package managers - it should show package managers for all platforms

**Comment by manyinsects** [comment]
This should be fixed on main, I can't reproduce it (using https://github.com/shadows-withal/weird-oranda-test)
