### ISSUE TITLE
Add support for additional pages as HTML

### ISSUE THREAD

**Issue by SaraVieira** [axodotdev/oranda#46]
users should also be able to have additional pages as HTML pages and we just copy them over

**Comment by SaraVieira** [comment]
@ashleygwilliams @Gankra @sarahghp 

Should we add this? We will have issues with styles since we will just be copying over whatever people add and it will not have our CSS files, how should we work around that?

**Comment by ashleygwilliams** [comment]
i do not think we should add this beyond what i specified in #102 and maybe other types of extensions like that

**Comment by SaraVieira** [comment]
Yeah good thinking, will close this
