### ISSUE TITLE
remove all unwraps and replace with error handling

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#48]

**Comment by SaraVieira** [comment]
Current unwraps:

- [ ] https://github.com/axodotdev/oranda/blob/main/src/site/mod.rs#L23
- [ ] https://github.com/axodotdev/oranda/blob/main/src/site/mod.rs#L49
- [x] https://github.com/axodotdev/oranda/blob/main/src/site/mod.rs#L62
- [ ] https://github.com/axodotdev/oranda/blob/main/src/site/css/mod.rs#L39
- [ ] https://github.com/axodotdev/oranda/blob/main/src/site/markdown/syntax_highlight/mod.rs#L35

**Comment by manyinsects** [comment]
Closing for now, we can take another look at this at some future point, but the current state of things looks pretty good.
