### ISSUE TITLE
order platforms alphabetically 

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#480]
<img width="340" alt="Screenshot 2023-06-27 at 6 26 32 PM" src="https://github.com/axodotdev/oranda/assets/1163554/e605ec8d-d0fe-4727-9d6e-8a4c9ffaebca">

**Comment by Plecra** [comment]
Hiya :) Going to have a look at this

**Comment by Plecra** [comment]
Aria poked around this a couple weeks back, and I think they saw the same sorted list of platforms I do on main:

![image](https://github.com/axodotdev/oranda/assets/60934058/73136a14-d1c8-4269-87da-65f96e3fee3b)

https://github.com/axodotdev/oranda/blob/13505ef71187f4b0b439735f242558dc0ecba437/src/site/artifacts/mod.rs#L16-L20

I'll see if I can confirm where this is being sorted, and check we're not just getting lucky hashes ;D

**Comment by manyinsects** [comment]
this PR https://github.com/axodotdev/oranda/pull/542 should guarantee that anything ordered passed into minijinja stays sorted, so hopefully that should help

**Comment by Plecra** [comment]
Hm, I think that may not work alone :) I just found the same code and I think the BTreeMap representation was actually *saving* us? The HashMap repr of `platforms_with_downloads: Platforms` might shuffle the platforms, and the BTreeMap was sorting them correctly. Using an IndexMap (which might happen if another crate enabled the `preserve_order` feature in the dependency tree) will maintain the incorrect sort produced by the HashMap.

**Comment by Plecra** [comment]
Oh even then we were getting lucky that the target triples had the same sort order as the display names! Adding a post process filter in the template is likely the easiest solution: https://docs.rs/minijinja/latest/minijinja/filters/fn.sort.html

I can PR that if you like?

**Comment by manyinsects** [comment]
that sounds good, go for it!
