### ISSUE TITLE
Workspace project support

### ISSUE THREAD

**Issue by jamesmunns** [axodotdev/oranda#493]
Hi there! I chatted privately with @ashleygwilliams about this, but I'd be very interested in using oranda for [mnemos](https://github.com/tosc-rs/mnemos) to replace the, uh, [current state of the art](https://mnemos-dev.jamesmunns.com/) of our landing page.

Mnemos is a workspace, and has a number of "internal" (developer facing) and "external" (user facing) libraries and applications. Having some way to have a "collection" of pages/projects/??? would be very neat!

Not sure if this is already tracked somewhere, but i'd be interested in trying oranda out again if this is a use case that is supported in the future.

Thanks!

**Comment by ashleygwilliams** [comment]
we were not yet tracking it anywhere but this is a feature we are all pretty excited about. we've heard the request in two forms, "workspace" and "org"- but the general idea is "multi-tenant" oranda. we can use this as a tracking issue and keep you up-to-date as we make progress :)
