### ISSUE TITLE
Documentation for "additional" package managers is missing/incorrect

### ISSUE THREAD

**Issue by tertsdiepraam** [axodotdev/oranda#520]
I was trying to make a page with preferred and additional package managers, but the docs seem to be inaccurate/incomplete. 

The [documentation about artifacts](https://github.com/axodotdev/oranda/blob/main/docs/src/configuration/artifacts.md) explains that package managers under `"hidden"` only show up on the dedicated install page, but that actually hides the installation method everywhere. Instead, the `"additional"` key is used for this purpose, but that is not mentioned in the docs as far as I can tell.

I ultimately figured this out by looking at the `oranda.json` in this repository, which uses `"additional"`.

**Comment by manyinsects** [comment]
oops, correct, will update asap

**Comment by tertsdiepraam** [comment]
Thank you!
