### ISSUE TITLE
Feature Request: Automatic site refresh with `oranda dev`

### ISSUE THREAD

**Issue by jamesmunns** [axodotdev/oranda#556]
Tools like `zola` have the ability to trigger a website refresh when operating in watching modes like `zola serve`. This causes the browser to refresh the page when the site has been rebuilt.

This is a minor quality of life feature, but is nice to avoid manual interaction when editing project contents.

**Comment by manyinsects** [comment]
for my own reference: IIRC, most tools that do this run a basic websockets server and inject a client snippet that listens to said websocket server, i've also seen some using HTTP/2 server push
