### ISSUE TITLE
workspaces: Provide markdown embed and preferred project(s)

### ISSUE THREAD

**Issue by manyinsects** [axodotdev/oranda#564]
Much like in the funding component, workspaces should be able to load content from a Markdown file, as well as have a notion to express that one member is the "main" or "preferred" member.

**Comment by manyinsects** [comment]
More details:

## Markdown embed

Both of these features really mirror the ones already in the funding configuration. The user should be able to set `workspaces.docs_path` (or some variation of that name), and oranda will render this into the workspace index page. `Page::new_from_both` can be used to quickly read a Markdown file (check how it's used with funding), and to provide its rendered content to a Jinja template.

## Preferred project(s)

You should be able to specify the slug(s) of multiple projects, and they'll be suggested first, in a larger/more prominent space on the workspace index page. This should also remove those projects from the "normal" listing that follows after. Again, Funding already does much of the same work, so that can be used as a good reference.

Here's a wireframe Ashley drew up:

![IMG_4752](https://github.com/axodotdev/oranda/assets/6445316/db4eb7e0-fcec-4135-99dd-e3178543ccde)

**Comment by mistydemeo** [comment]
> Page::new_from_both can be used to quickly read a Markdown file (check how it's used with funding), and to provide its rendered content to a Jinja template.

Maybe I'm misinterpreting which example from funding you're mentioning, but it looks like funding is doing this to render HTML and then renders it in its template: https://github.com/axodotdev/oranda/blob/main/src/data/funding.rs#L85-L89

Is that the model you're suggesting following?

**Comment by manyinsects** [comment]
Ah, I misremembered, then, if funding does load their Markdown like this, it's probably better to also do it in the workspace context, for encapsulation's sake.
