### ISSUE TITLE
Changelog docs missing "get from github" example

### ISSUE THREAD

**Issue by jamesmunns** [axodotdev/oranda#611]
Somewhere between version 0.3.0-prerelease.5 and 0.3.0-prerelease.6 oranda stopped showing the "body" of changelogs.

Before (up to .5):

<img width="1202" alt="Screenshot 2023-08-26 at 00 26 12" src="https://github.com/axodotdev/oranda/assets/2097964/6fd53760-0190-4958-906e-c3b8d4d5860c">

Starting in .6 (and including release 0.3.1):

<img width="1197" alt="Screenshot 2023-08-26 at 00 20 21" src="https://github.com/axodotdev/oranda/assets/2097964/bc87392b-730d-4a7d-b6fe-448f3a621577">

I haven't nailed down the specific commit, but with binstall that is the released version range.

**Comment by jamesmunns** [comment]
Haha, j/k, this was an intentional design choice.

Adding this makes it all better:

```json
  "components": {
    "changelog": {
      "read_changelog_file": false
    }
  }
```

That being said, it's not mentioned [in the changelog docs](https://opensource.axo.dev/oranda/book/configuration/changelog.html), and it does mean that we need to manually disable changelogs in all children projects.

I'll keep this open to maybe track:

* Adding docs for this
* Maybe discuss the impact of enabling changelogs for ALL subprojects, which might not be released independently.

This is probably an area where mnemos is weird because:

* we don't actually release our children crates (which might have their own changelogs?)
* we do sort of "whole repo rolling release" things just for progress.

**Comment by jamesmunns** [comment]
Also I see a lot of this while building:

```
↪ >o_o< INFO: Found 52 paths to watch, starting watch...
↪ >o_o< INFO: Workspace detected, gathering info...
↪ >o_o< INFO: Building 14 workspace member(s)...
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
MnemosProjectOverview ↪ >o_o< INFO: Building components: changelog, mdbook
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
Fetching from proxy encountered an error:
 HTTP status client error (403 Forbidden) for url (https://octolotl.axodotdev.host/releases/tosc-rs/mnemos).
 Falling back to GitHub directly...
↪ >o_o< INFO: Building workspace index page...
✓ >o_o< SUCCESS: Your site builds are located in `public`.
✓ >o_o< SUCCESS: Your project is available at: http://127.0.0.1:7979
```

**Comment by jamesmunns** [comment]
Also, the first thing I tried was to put `"changelog": false` in the workspace, then ONLY enabling the changelog w/ "pull from github" for our overview project, but I think that didn't work (no changelog generated for the overview project).

**Comment by tertsdiepraam** [comment]
I was just wondering why the changelog wasn't showing up on our oranda site. Thanks for the hint!

I think it would be nice if `oranda` tried to read the changelog from GitHub (or similar) automatically if there is no `CHANGELOG.md` present. Otherwise, just some documentation on this would be great! Additionally, it might be nice if `oranda` emits a warning (maybe even an error) if `read_changelog_file` is set to `true`, but no file is found.
