### ISSUE TITLE
Blockquotes are broken in raw markdown

### ISSUE THREAD

**Issue by SaraVieira** [axodotdev/oranda#63]
Doing something like

```
> Hello
```

Is not styled properly

<img width="754" alt="CleanShot 2023-01-12 at 18 43 38@2x" src="https://user-images.githubusercontent.com/1051509/212140399-bc29749c-ad0a-4da7-9ccd-27df7cba85f0.png">

**Comment by sarahghp** [comment]
Based on looking in the inspector, it seemed like this got transformed into `<p> > Blah </p>` and I am not totally sure why.
