### ISSUE TITLE
oranda is available via scoop

### ISSUE THREAD

**Issue by simonsan** [axodotdev/oranda#635]
Could you also add that to the release notes, successfully updated today :)

```console
scoop install oranda
```

![2023-09-12 04_14_23-Release 0 4 0 - 2023-09-11 · axodotdev_oranda — Mozilla Firefox](https://github.com/axodotdev/oranda/assets/14062932/d2d915b7-c34e-4ebc-be55-9ccf92cfdf9a)

**Comment by manyinsects** [comment]
Oh, you're right! The release notes on the website can't really be changed anymore without some awful hand-editing, but I'll edit it into the GitHub release notes. Thank you for your effort!

**Comment by manyinsects** [comment]
Done!
