### ISSUE TITLE
oranda build: "failed to read asset from" No such file or directory (os error 2)

### ISSUE THREAD

**Issue by konstin** [axodotdev/oranda#639]
I tried `oranda build` (0.4.1) as shown on the website and the book on https://github.com/konstin/gourgeist 28c8126fad9b465b4ba6bd9170721594b6a04ed3:
```console
$ oranda build
↪ >o_o< INFO: Building components: artifacts, changelog
  × failed to read asset from
  ╰─▶ No such file or directory (os error 2)
  help: Make sure your path is relative to your oranda config or project manifest file.
```
I'm missing the information about what failed because it doesn't show the missing path

**Comment by ashleygwilliams** [comment]
hey @konstin! this is a terrible error message- sorry about that! let me dig in and see what's up

**Comment by manyinsects** [comment]
heya! sorry for that terrible error - that was an oversight with how we handle path fallbacks. I'll send a PR fixing that error to actually display the missing filename, which in your case was the readme file. one current "hard" requirement of oranda is that you kind of need a README file, this stems from the very first version, when literally all it did was render README files. oranda can do way more now, so I don't think a readme should be a requirement anymore.

**Comment by manyinsects** [comment]
Posted https://github.com/axodotdev/oranda/pull/640, this should allow you to use oranda without a README present, and have much nicer error messages for all other paths that it expects to exist (mostly when you tell it explicitly that something should be at a specific path).

**Comment by manyinsects** [comment]
I just released a new prerelease that contains the above PR, feel free to test it out, and let us know if you have any further issues or suggestions! https://github.com/axodotdev/oranda/releases/tag/v0.5.0-prerelease.1

**Comment by konstin** [comment]
That fixes it, thank you!
