### ISSUE TITLE
Lots of JS running during scrolling on release page

### ISSUE THREAD

**Issue by mstange** [axodotdev/oranda#688]
I'm not sure if this is the right place to file this.

Steps to reproduce:
 1. Go to https://public.axodotdev.host/releases/github/axodotdev/cargo-dist/cargo-dist/0.12.0
 2. Start a profiler.
 3. Scroll up and down.

Expected results:
Not much JS running.

Actual results:
Lots of JS running, causing checkerboarding in Firefox: https://share.firefox.dev/4cq7G8a

The profile shows that there are mutation observers installed, and that some attributes and transform styles are set in response to `scroll` events. The mutation observers make the attribute modifications very slow.
I can't investigate much further because the nuxt code is minified.

**Comment by Gankra** [comment]
looks like this is entirely due to the "popper" tooltips library we're using... wtf

**Comment by Gankra** [comment]
fixed in the actual repo, will deploy on monday

**Comment by ashleygwilliams** [comment]
(i've merged the fix and it's currently deploying)

**Comment by ashleygwilliams** [comment]
deployed and appears to be fixed but definitely follow up or file more issues with other stuff you might run into!

**Comment by mstange** [comment]
Looks great now, thanks for the fix!
