### ISSUE TITLE
Add oranda theme dev

### ISSUE THREAD

**Issue by sarahghp** [axodotdev/oranda#71]
Add command to build & serve oranda with a link to a theme config that includes all possible items (repo bar, multiple pages, README with markdown elements). Predicated on https://github.com/axodotdev/oranda/issues/70

**Comment by SaraVieira** [comment]
Worked on:

https://github.com/axodotdev/oranda/pull/79
https://github.com/axodotdev/oranda/pull/96
https://github.com/axodotdev/oranda/pull/77
https://github.com/axodotdev/oranda/pull/94
