### ISSUE TITLE
focus state for interactive elements needs styling

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/oranda#87]
you can repro this by opening an oranda page and hitting tab which brings the first interactive element into an active state
<img width="719" alt="Screen Shot 2023-01-21 at 8 31 32 AM" src="https://user-images.githubusercontent.com/1163554/213871551-54363023-a0f8-4459-8371-93e7de0b79f4.png">

**Comment by ashleygwilliams** [comment]
<img width="160" alt="Screen Shot 2023-01-21 at 8 34 11 AM" src="https://user-images.githubusercontent.com/1163554/213871602-dda9d4a6-1648-41af-8d99-ed3ba89b5310.png">
 looks like this is also the case for the "nav" `li`s

**Comment by sarahghp** [comment]
This is the browser default. I believe it is more correctly characterized as a feature request.

**Comment by sarahghp** [comment]
This is browser-default behavior. (The color is different in Firefox but actually harder to see.) I would  need to do research to figure out a way to do this that is correct for accessibility and even whether it is something that people who use keyboard navigation have opinions about.

**Comment by ashleygwilliams** [comment]
Yes, I know this is the browser default behavior, hence "needs styling". I would recommend just adding some padding or changing the colors so it looks a bit better and more intentional.

**Comment by ashleygwilliams** [comment]
both [css tricks](https://css-tricks.com/almanac/properties/o/outline/) and [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus#accessibility_concerns) seem to cover this well:
- the important thing is to not *remove them*- their existence (aka something that clearly indicates what element is in focus) is the feature
- they should be visually distinct (3:1 contrast), (so the fact that they are hard to see on Firefox is not good)

MDN links to [this article from deque](https://www.deque.com/blog/give-site-focus-tips-designing-usable-focus-indicators/), which has a lot of good info. i don't think we need research beyond this to style this for v1- again based on everything i've read in the last 15- a high contrast outline, within our color scheme, with some improved padding should be 100% aligned with accessibility needs.
