### ISSUE TITLE
Create artifacts downloads

### ISSUE THREAD

**Issue by SaraVieira** [axodotdev/oranda#89]
This will involves many steps:

### Common

- [x] Create system names so that they can be used everywhere
- [x] create detect-os js file
- [x] Show download link for correct system
- [ ] Create artifacts as page with table that includes all options

### Cargo dist

- [x] use https://github.com/axodotdev/cargo-dist/blob/v0.2.2-prerelease6/cargo-dist-schema/src/lib.rs to parse json
- [x] In cargo dist add curl
- [x] When cargo dist is true get manifest
- [x] windows downloads the ps1 installer
- [x] add link to sourcemap on windows
- [x] add installer hint to each system

### Binaries

- [ ] Allow hashmap where the keys must be a system type we return from detect-os
- [ ] Show correct download link
- [ ] Add link to artifacts created

### Type

```ts
type Distributables = {
	link_downloads: Bool
	// requires repo
	cargo_dist: true,
	package_managers: {
		[string]: ""
	},
	binaries: {
		linux: ""
	}
}
```

**Comment by ashleygwilliams** [comment]
closed by #99

**Comment by SaraVieira** [comment]
Reopened as we are missing binaries and package managers

**Comment by ashleygwilliams** [comment]
is this closable now, @SaraVieira ?

**Comment by ashleygwilliams** [comment]
closing as i believe this is complete.
