### ISSUE TITLE
oranda serve does not play nicely with `pathprefix`

### ISSUE THREAD

**Issue by sarahghp** [axodotdev/oranda#90]
![pages](https://user-images.githubusercontent.com/1477362/214043639-ba07dc40-f200-4071-a274-eaebd9075131.gif)

**Comment by SaraVieira** [comment]
oh locally it doesn't, we have a path prefix for github pages that's why we have the dev one because that one will work locally as we don't need to deploy it

**Comment by ashleygwilliams** [comment]
recently, @SaraVieira added a feature that allows users who are serving a page from a non-root URL to provide a path-prefix to allow links to work correctly. it looks like this (clearly) causes issues with `oranda serve` which uses a root URL to preview the page. 

to remedy this, i think we should have `oranda serve` serve from a non-root URL, e.g. `localhost:7979/pathprefix`. we can redirect `localhost:7979` to `localhost:7979/pathprefix` and print `localhost:7979/pathprefix` to the screen to make it easier for end users to go to the right preview. 

alternatively we could not use the `pathprefix` in the "dev build" i think this is the weaker of the two options for a few reasons:
- widens gap between dev and prod 
- requires 2 builds, dev and prod

cons to serve accounting for the pathprefix:
- if folks use something other than serve, it won't account for this

**Comment by SaraVieira** [comment]
I think this is the way to go and since axum supports routes we should be able to do this quite easily
