### ISSUE TITLE
document static dir

### ISSUE THREAD

**Issue by sarahghp** [axodotdev/oranda#91]
<img width="1011" alt="Screen Shot 2023-01-23 at 2 59 27 PM" src="https://user-images.githubusercontent.com/1477362/214058203-6526cba0-74ab-4c9e-95c9-03e6e340493a.png">

<img width="907" alt="Screen Shot 2023-01-23 at 2 49 53 PM" src="https://user-images.githubusercontent.com/1477362/214058194-cfcf3f37-52a8-41ba-adca-1fb8321c87a5.png">

(It's possible this is already covered; please close if you know this.)

**Comment by ashleygwilliams** [comment]
i believe you need to put the image in a `static` dir, https://github.com/axodotdev/oranda/blob/219a8316c515b2156b2679ef0d0a6f09fc9cba43/src/site/mod.rs#L60

it's not yet documented, and we should do that.
