### ISSUE TITLE
theme: update to style sub-lists

### ISSUE THREAD

**Issue by sarahghp** [axodotdev/oranda#93]
The items in the sublists should have distinct `list-style-type`s. I _think_ part of the answer may be to reset overrides rather than explicitly adding rules.

<img width="786" alt="Screen Shot 2023-01-23 at 5 23 33 PM" src="https://user-images.githubusercontent.com/1477362/214093322-c7fd632c-1fce-41c7-987a-102cd9798e88.png">

**Comment by SaraVieira** [comment]
this is done
